name: Update gist with Steam Playtime

on:
  push:
    branches: 
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: "0 * * * *"
    

jobs:

  build:
    name: Upddate-gist
    runs-on: ubuntu-latest
    env:
          GH_TOKEN: 309da2e38a0eaf8d006bbefdf134d1c2ebc23e1f
          GIST_ID: 7dd9705e7927883a634d337e39b59d28
          STEAM_API_KEY: 7E18E9AA45FA7810965CDC5743FE2990
          STEAM_ID: STEAM_0:1:102677615
          UPDATE_OPTION: MARKDOWN
          MARKDOWN_FILE: README.md
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      
    - name: Update-gist
      run:  go run ./cmd/box/main.go

